Config changes

diff --git a/.github/workflows/deploy-to-minikube-github-actions.yaml b/.github/workflows/deploy-to-minikube-github-actions.yaml
--- a/.github/workflows/deploy-to-minikube-github-actions.yaml
+++ b/.github/workflows/deploy-to-minikube-github-actions.yaml
@@ -8,8 +8,15 @@ jobs:
     name: build Node.js Docker Image and deploy to minikube
     steps:
     - uses: actions/checkout@v2
-    - name: Start minikube
-      uses: medyagh/setup-minikube@master
+    - name: Start Minikube
+      run: minikube start --driver=docker
+
+    - name: Wait for Minikube to be ready
+      run: |
+        for i in {1..30}; do
+          minikube status | grep -q 'Running' && break
+          sleep 5
+        done
     - name: Check Minikube Status
       run: minikube status
     - name: Try the cluster !
@@ -23,6 +30,9 @@ jobs:
           docker images
     - name: Print Minikube Docker Env
       run: minikube -p minikube docker-env
+    - name: Check Minikube logs if failure
+      if: failure()
+      run: cat /tmp/minikube_service_ba873920b9ac8d1e0c86efebfbdc1732e36079e5_0.log || echo "Log not found"
     - name: Deploy to minikube
       run:
         kubectl apply -f k8s-node-app.yaml
@@ -30,4 +40,3 @@ jobs:
       run: |
           minikube service list
           minikube service nodejs-app --url
-          cat /tmp/minikube_service_ba873920b9ac8d1e0c86efebfbdc1732e36079e5_0.log
